### ISSUE TITLE
Is this still a supported project?

### ISSUE THREAD

**Issue by judgewest2000** [carbon-native/carbon-native#6]
Howdy,

I'm just wondering if this project is still supported or not.

When I try to implement I'm getting...

`undefined is not an object (evaluating '_react.PropTypes.onOfType)`

Thank you

**Comment by tylerbuchea** [comment]
It is still a supported project. What version of RN/React are you using? Might be a breaking change.

**Comment by judgewest2000** [comment]
Hi.
0.49 or whatever the latest is. Brand new project so not a lot else going on. 

Thank you

**Comment by tylerbuchea** [comment]
Okay thanks for the feedback we'll check it and get a bug fix out soon as we can.

**Comment by joshbuchea** [comment]
Hi @judgewest2000,

Yes, this project is still supported. Although I admit it hasn't been getting the attention it deserves. We're working on a new release with some nice improvements that should be out very soon.

In regards to your issue, it looks like we were still importing `PropTypes` from `react` instead of from `prop-types`.  We resolved the issue and the fix has been pushed to the repo and npm.

**Comment by judgewest2000** [comment]
Magic.

Thank you
